EnabledChannels:
    -'693207926692642826'
    -'707248041928949891'
UnbanCommand: "!unban"
InfoCommand: "!baninfo"
ShowInfoAfterUnban: true
RequireConfirmation: true
DateFormat: "HH:mm dd-MM-yyyy" #see https://docs.oracle.com/javase/10/docs/api/java/text/SimpleDateFormat.html
Role: "707310286251622492"